/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:029ad28c-3fc4-4bb7-812b-bd1615e6addc",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_jQE4hguUx",
    "aws_user_pools_web_client_id": "5jdtju84thu3h5ohl3lg7j6cqt",
    "oauth": {}
};


export default awsmobile;
